// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  CONCEPT_GRAPH_DB: SmartSql;
  GRAPH_PROCESSOR: ServiceStub<import('../graph-processor/index.js').default>;
  logger: Logger;
  MEDIA_GENERATOR: ServiceStub<import('../media-generator/index.js').default>;
  mem: KvCache;
  MEMORY_MANAGER: ServiceStub<import('../memory-manager/index.js').default>;
  NODE_MEDIA_STORAGE: SmartBucket;
  tracer: Tracer;
  USER_SESSIONS: SmartMemory;
}
